### ISSUE TITLE
Add concise information about sent telemetry to README

### ISSUE THREAD

**Issue by Jaakkonen** [redhat-developer/vscode-commons#23]
It looks like a telemetry option was added to this extension. I appreciate the transparency of making the telemetry data opt-in. However as this is a developer facing extension I think the documentation could look more like it.

I propose adding something like follows to the README.

```
# Telemetry data
## Explanation of sent telemetry data
Redhat vscode-commons extension sends telemetry data to `<Telemetry URL>` if following setting is `true` in `settings.json`:
\```
"redhat.telemetry.enabled": true  // Set to `false` do disable telemetry
\```

The telemetry consists of following events:
\```
// TODO: Add JSON structures of actual telemetry events
{
  "event": "started",
  "extension": "namespace.plugin-name",
  "platform": "code - oss"
}
\```

## Storage of telemetry data
Telemetry data is stored on Redhat servers hosted on <hoster name> and is kept there for <X> months.
Access is restricted to <list of people / teams>.

Telemetry data is not sent to logging systems or data lake services that have longer data retention span or wider access base than specified above.
```

Additionally I think making a notification to ask for answering to a survey when telemetry is opted out would be helpful for some users who dislike automatic telemetry but are willing to share their experiences in a manual controlled manner.

**Comment by fbricon** [comment]
@Jaakkonen thanks for your input. Not sure we'll add the json structures, but pretty much everything is described in https://github.com/redhat-developer/vscode-commons/blob/master/USAGE_DATA.md, available from the readme. If it helps putting that in the readme, I'm fine with it.

**Comment by Jaakkonen** [comment]
You probably don't have too much time to communicate about the usage in more technical way which would also increase maintenance burden. The usage data markdown document however answers the question pretty well. Closing.
